/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email and password for an access token.
         *
         *     The OAuth2 form calls the field `username`; we carry the email in it.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description List the active products in the public catalogue.
         */
        get: operations["list_products_products_get"];
        put?: never;
        /**
         * Create Product
         * @description Create a product. Admin only.
         */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product
         * @description Product detail, including the stores where it is available.
         */
        get: operations["get_product_products__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Product
         * @description Permanently delete a product, its images and store links. Admin only.
         */
        delete: operations["delete_product_products__product_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Product
         * @description Partially update a product. Admin only.
         */
        patch: operations["update_product_products__product_id__patch"];
        trace?: never;
    };
    "/products/{product_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Product Image
         * @description Upload an image for a product. The first one becomes the cover.
         */
        post: operations["upload_product_image_products__product_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/images/{image_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Product Image Cover
         * @description Make this image the product's cover. Admin only.
         */
        patch: operations["set_product_image_cover_products__product_id__images__image_id__cover_patch"];
        trace?: never;
    };
    "/products/{product_id}/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Product Image
         * @description Delete an image from the product and from the bucket. Admin only.
         */
        delete: operations["delete_product_image_products__product_id__images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Product categories, in the display order set by the admin.
         */
        get: operations["list_categories_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description Create a category. Admin only.
         */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Category
         * @description Delete a category. Refused while products still use it. Admin only.
         */
        delete: operations["delete_category_categories__category_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Category
         * @description Partially update a category. Admin only.
         */
        patch: operations["update_category_categories__category_id__patch"];
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Units
         * @description Selling units (kg, unit, 25kg bag, ...).
         */
        get: operations["list_units_units_get"];
        put?: never;
        /**
         * Create Unit
         * @description Create a selling unit. Admin only.
         */
        post: operations["create_unit_units_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Unit
         * @description Delete a unit. Refused while products still use it. Admin only.
         */
        delete: operations["delete_unit_units__unit_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Unit
         * @description Partially update a unit. Admin only.
         */
        patch: operations["update_unit_units__unit_id__patch"];
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stores
         * @description Company stores, with address and opening hours.
         */
        get: operations["list_stores_stores_get"];
        put?: never;
        /**
         * Create Store
         * @description Create a store. Admin only.
         */
        post: operations["create_store_stores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_stores__store_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Store
         * @description Delete a store. Refused while products or employees reference it.
         */
        delete: operations["delete_store_stores__store_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Store
         * @description Partially update a store (address, opening hours, ...). Admin only.
         */
        patch: operations["update_store_stores__store_id__patch"];
        trace?: never;
    };
    "/stores/{store_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Store Image
         * @description Set the store photo, replacing any previous one. Admin only.
         */
        put: operations["upload_store_image_stores__store_id__image_put"];
        post?: never;
        /**
         * Delete Store Image
         * @description Remove the store photo. Admin only.
         */
        delete: operations["delete_store_image_stores__store_id__image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Staff members and their contact details.
         */
        get: operations["list_employees_employees_get"];
        put?: never;
        /**
         * Create Employee
         * @description Create an employee. Admin only.
         */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Employee
         * @description Delete an employee. Admin only.
         */
        delete: operations["delete_employee_employees__employee_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Employee
         * @description Partially update an employee. Admin only.
         */
        patch: operations["update_employee_employees__employee_id__patch"];
        trace?: never;
    };
    "/employees/{employee_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Employee Image
         * @description Set the employee photo, replacing any previous one. Admin only.
         */
        put: operations["upload_employee_image_employees__employee_id__image_put"];
        post?: never;
        /**
         * Delete Employee Image
         * @description Remove the employee photo. Admin only.
         */
        delete: operations["delete_employee_image_employees__employee_id__image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Announcements
         * @description Active announcements (e.g. holiday closures), most recent first.
         */
        get: operations["list_announcements_announcements_get"];
        put?: never;
        /**
         * Create Announcement
         * @description Create an announcement. Admin only.
         */
        post: operations["create_announcement_announcements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/{announcement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Announcement
         * @description Delete an announcement. Admin only.
         */
        delete: operations["delete_announcement_announcements__announcement_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Announcement
         * @description Partially update an announcement. Admin only.
         */
        patch: operations["update_announcement_announcements__announcement_id__patch"];
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Posts
         * @description Content feed: news, photos and social embeds, newest first.
         */
        get: operations["list_posts_posts_get"];
        put?: never;
        /**
         * Create Post
         * @description Create a post. The photo, if any, is uploaded separately. Admin only.
         */
        post: operations["create_post_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Post
         * @description Delete a post and its photo. Admin only.
         */
        delete: operations["delete_post_posts__post_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Post
         * @description Partially update a post. Admin only.
         */
        patch: operations["update_post_posts__post_id__patch"];
        trace?: never;
    };
    "/posts/{post_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Post Image
         * @description Set the post photo, replacing any previous one. Admin only.
         */
        put: operations["upload_post_image_posts__post_id__image_put"];
        post?: never;
        /**
         * Delete Post Image
         * @description Remove the post photo. Admin only.
         */
        delete: operations["delete_post_image_posts__post_id__image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/about-us": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get About Us
         * @description Company profile text, social links and video.
         */
        get: operations["get_about_us_about_us_get"];
        /**
         * Save About Us
         * @description Create or replace the 'Sobre Nós' content. Admin only.
         */
        put: operations["save_about_us_about_us_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AboutUsRead */
        AboutUsRead: {
            /** Id */
            id: number;
            /** Tagline */
            tagline: string | null;
            /** Text */
            text: string;
            /** Email */
            email: string | null;
            /** Video Url */
            video_url: string | null;
            /** Facebook Url */
            facebook_url: string | null;
            /** Instagram Url */
            instagram_url: string | null;
        };
        /**
         * AboutUsWrite
         * @description Singleton: the admin form always submits every field.
         */
        AboutUsWrite: {
            /** Tagline */
            tagline?: string | null;
            /** Text */
            text: string;
            /** Email */
            email?: string | null;
            /** Video Url */
            video_url?: string | null;
            /** Facebook Url */
            facebook_url?: string | null;
            /** Instagram Url */
            instagram_url?: string | null;
        };
        /** AnnouncementCreate */
        AnnouncementCreate: {
            /** Title */
            title: string;
            /** Message */
            message: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AnnouncementRead */
        AnnouncementRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnnouncementUpdate */
        AnnouncementUpdate: {
            /** Title */
            title?: string | null;
            /** Message */
            message?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_employee_image_employees__employee_id__image_put */
        Body_upload_employee_image_employees__employee_id__image_put: {
            /**
             * File
             * @description JPEG, PNG or WebP, up to 5 MB
             */
            file: string;
        };
        /** Body_upload_post_image_posts__post_id__image_put */
        Body_upload_post_image_posts__post_id__image_put: {
            /**
             * File
             * @description JPEG, PNG or WebP, up to 5 MB
             */
            file: string;
        };
        /** Body_upload_product_image_products__product_id__images_post */
        Body_upload_product_image_products__product_id__images_post: {
            /**
             * File
             * @description JPEG, PNG or WebP, up to 5 MB
             */
            file: string;
            /**
             * Is Cover
             * @default false
             */
            is_cover: boolean;
        };
        /** Body_upload_store_image_stores__store_id__image_put */
        Body_upload_store_image_stores__store_id__image_put: {
            /**
             * File
             * @description JPEG, PNG or WebP, up to 5 MB
             */
            file: string;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Display Order */
            display_order?: number | null;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Contact */
            contact: string;
            /** Store Id */
            store_id: number;
        };
        /** EmployeeRead */
        EmployeeRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Contact */
            contact: string;
            store: components["schemas"]["StoreSummary"];
            /** Image Url */
            readonly image_url: string | null;
        };
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Contact */
            contact?: string | null;
            /** Store Id */
            store_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PostCreate */
        PostCreate: {
            /** Title */
            title: string;
            /** Text */
            text?: string | null;
            /** Embed Url */
            embed_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** PostRead */
        PostRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string | null;
            /** Embed Url */
            embed_url: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** PostUpdate */
        PostUpdate: {
            /** Title */
            title?: string | null;
            /** Text */
            text?: string | null;
            /** Embed Url */
            embed_url?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Price */
            price: number | string;
            /** Discount Price */
            discount_price?: number | string | null;
            /** Category Id */
            category_id: number;
            /** Unit Id */
            unit_id: number;
            /** Embed Url */
            embed_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /** Display Order */
            display_order?: number | null;
            /**
             * Store Ids
             * @default []
             */
            store_ids: number[];
        };
        /** ProductDetail */
        ProductDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Price */
            price: string;
            /** Discount Price */
            discount_price: string | null;
            /** Embed Url */
            embed_url: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Featured */
            is_featured: boolean;
            /** Display Order */
            display_order: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            category: components["schemas"]["CategoryRead"];
            unit: components["schemas"]["UnitRead"];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ProductImageRead"][];
            /**
             * Stores
             * @default []
             */
            stores: components["schemas"]["StoreSummary"][];
        };
        /** ProductImageRead */
        ProductImageRead: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Is Cover */
            is_cover: boolean;
            /** Image Url */
            readonly image_url: string;
        };
        /** ProductRead */
        ProductRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Price */
            price: string;
            /** Discount Price */
            discount_price: string | null;
            /** Embed Url */
            embed_url: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Featured */
            is_featured: boolean;
            /** Display Order */
            display_order: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            category: components["schemas"]["CategoryRead"];
            unit: components["schemas"]["UnitRead"];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ProductImageRead"][];
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Price */
            price?: number | string | null;
            /** Discount Price */
            discount_price?: number | string | null;
            /** Category Id */
            category_id?: number | null;
            /** Unit Id */
            unit_id?: number | null;
            /** Embed Url */
            embed_url?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Featured */
            is_featured?: boolean | null;
            /** Display Order */
            display_order?: number | null;
            /** Store Ids */
            store_ids?: number[] | null;
        };
        /** StoreCreate */
        StoreCreate: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StoreRead
         * @description Full form, for the stores/contacts page.
         */
        StoreRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: unknown;
            } | null;
            /** Image Url */
            readonly image_url: string | null;
        };
        /**
         * StoreSummary
         * @description Short form, for nesting inside a product or an employee.
         */
        StoreSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /** StoreUpdate */
        StoreUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: unknown;
            } | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UnitCreate */
        UnitCreate: {
            /** Name */
            name: string;
        };
        /** UnitRead */
        UnitRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** UnitUpdate */
        UnitUpdate: {
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category_id?: number | null;
                /** @description Filter by store */
                store_id?: number | null;
                /** @description Only featured products */
                is_featured?: boolean | null;
                /** @description Admin only: also return inactive products */
                include_inactive?: boolean;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_product_image_products__product_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_product_image_products__product_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_product_image_cover_products__product_id__images__image_id__cover_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_image_products__product_id__images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRead"][];
                };
            };
        };
    };
    create_unit_units_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unit_units__unit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_unit_units__unit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stores_stores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"][];
                };
            };
        };
    };
    create_store_stores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_stores__store_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_store_stores__store_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_store_stores__store_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_store_image_stores__store_id__image_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_store_image_stores__store_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_store_image_stores__store_id__image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_employees_get: {
        parameters: {
            query?: {
                /** @description Filter by store */
                store_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee_employees__employee_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_employee_image_employees__employee_id__image_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_employee_image_employees__employee_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee_image_employees__employee_id__image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_announcements_announcements_get: {
        parameters: {
            query?: {
                /** @description Admin only: also return inactive announcements */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_announcement_announcements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_announcement_announcements__announcement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                announcement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_announcement_announcements__announcement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                announcement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_posts_get: {
        parameters: {
            query?: {
                /** @description Admin only: also return hidden posts */
                include_inactive?: boolean;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_post_image_posts__post_id__image_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_post_image_posts__post_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_image_posts__post_id__image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_about_us_about_us_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutUsRead"];
                };
            };
        };
    };
    save_about_us_about_us_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AboutUsWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutUsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
